# Generated by Django 5.1 on 2024-12-01 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField(default=0)),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('m2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('correo', models.EmailField(max_length=100)),
                ('usuario_pc', models.CharField(max_length=100)),
                ('clave_pc', models.CharField(max_length=100)),
                ('nombre_pc', models.CharField(max_length=100)),
                ('nombre_anyDesk', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('centro_costo', models.CharField(max_length=6)),
                ('supervisor', models.CharField(max_length=20)),
                ('codSii', models.TextField()),
                ('almacen', models.CharField(max_length=4)),
                ('codSAP', models.CharField(max_length=5)),
                ('caja', models.IntegerField()),
                ('ppl_epos', models.CharField(max_length=2)),
                ('rtpro', models.BooleanField(default=False)),
                ('vyv_pos', models.BooleanField(default=False)),
                ('tel', models.CharField(max_length=32)),
                ('cel', models.CharField(max_length=32)),
                ('numero_rtpro', models.CharField(max_length=3)),
                ('version_plugins', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('servidor', models.BooleanField(blank=True, null=True)),
                ('marca_tienda', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvCab',
            fields=[
                ('idInventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('store', models.CharField(max_length=3)),
                ('nota_inv', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('estado_conteo', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.IntegerField()),
                ('cod_plano', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.invcab')),
            ],
        ),
        migrations.CreateModel(
            name='InvDet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zona', models.IntegerField()),
                ('sku', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('username', models.CharField(max_length=21)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioApp.invcab')),
            ],
        ),
    ]
