# Generated by Django 5.1 on 2024-10-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField(default=0)),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('m2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('correo', models.EmailField(max_length=100)),
                ('usuario_pc', models.CharField(max_length=100)),
                ('clave_pc', models.CharField(max_length=100)),
                ('nombre_pc', models.CharField(max_length=100)),
                ('nombre_anyDesk', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('centro_costo', models.CharField(max_length=6)),
                ('supervisor', models.CharField(max_length=20)),
                ('codSii', models.TextField()),
                ('almacen', models.CharField(max_length=4)),
                ('codSAP', models.CharField(max_length=5)),
                ('caja', models.IntegerField()),
                ('ppl_epos', models.CharField(max_length=2)),
                ('rtpro', models.BooleanField(default=False)),
                ('vyv_pos', models.BooleanField(default=False)),
                ('tel', models.CharField(max_length=32)),
                ('cel', models.CharField(max_length=32)),
                ('numero_rtpro', models.CharField(max_length=3)),
                ('version_plugins', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
                ('servidor', models.BooleanField(blank=True, null=True)),
                ('marca_tienda', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
