# Generated by Django 5.1 on 2024-12-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosRtpro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ventana', models.CharField(blank=True, max_length=10, null=True)),
                ('temp_comercial', models.CharField(blank=True, max_length=50, null=True)),
                ('coleccion', models.CharField(blank=True, max_length=50, null=True)),
                ('familia', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('lppv', models.IntegerField(blank=True, null=True)),
                ('lpmay', models.IntegerField(blank=True, null=True)),
                ('lpof', models.IntegerField(blank=True, null=True)),
                ('lpout', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
