# Generated by Django 5.1 on 2024-12-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0002_productosrtpro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosrtpro',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='productosrtpro',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='productosrtpro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
