# Generated by Django 5.1 on 2024-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioApp', '0005_alter_repositorioventas_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='repositorioVentasTienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invc_sid', models.CharField(max_length=50)),
                ('cust_sid', models.CharField(max_length=50)),
                ('create_date', models.DateField()),
                ('store_code', models.CharField(max_length=50)),
                ('type_dte', models.CharField(max_length=50)),
                ('tracking_no', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
